# This is a basic workflow to help you get started with Actions

nome: Gerar Dados
em: 
 horário: #execute A cada 12 horas
  - cron: "* */12 * *"
Workflow_dispatch:

Vagas:
 construir:
   nome: Empregos para atualizar dados
    em funcionamento: ubuntu-mais recente
passos:
 Animação #cobra
- usos: Platane/snk@master
  Id: snake-gif
com: 
   github_user_name: guilhermevieirapena
   svg_out_patch: dist/github-contribution-grid-snake.svg

- usos: crazy-max/ghaction-github-pages@v2.1.3
 com:
   ramo alvo: saída
   build_dir: dist
env:
GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN}}
